//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgroStoreEntities1 : DbContext
    {
        public AgroStoreEntities1()
            : base("name=AgroStoreEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblCarrier> tblCarrier { get; set; }
        public virtual DbSet<tblCategory> tblCategory { get; set; }
        public virtual DbSet<tblCustomer> tblCustomer { get; set; }
        public virtual DbSet<tblOrder> tblOrder { get; set; }
        public virtual DbSet<tblOrderDetails> tblOrderDetails { get; set; }
        public virtual DbSet<tblPayment> tblPayment { get; set; }
        public virtual DbSet<tblProduct> tblProduct { get; set; }
        public virtual DbSet<tblSupplier> tblSupplier { get; set; }
        public virtual DbSet<vwCarrier> vwCarrier { get; set; }
        public virtual DbSet<vwCategory> vwCategory { get; set; }
        public virtual DbSet<vwCustomer> vwCustomer { get; set; }
        public virtual DbSet<vwOrder> vwOrder { get; set; }
        public virtual DbSet<vwOrderDetails> vwOrderDetails { get; set; }
        public virtual DbSet<vwPayment> vwPayment { get; set; }
        public virtual DbSet<vwProduct> vwProduct { get; set; }
        public virtual DbSet<vwSupplier> vwSupplier { get; set; }
    }
}
